/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: {
          base:     'var(--surface-base)',
          DEFAULT:  'var(--surface-default)',
          elevated: 'var(--surface-elevated)',
          card:     'var(--surface-card)',
          overlay:  'var(--surface-overlay)',
          hover:    'var(--surface-hover)',
          glass:    'var(--surface-glass)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          hover:   'var(--accent-hover)',
          pressed: 'var(--accent-pressed)',
          deep:    'var(--accent-deep)',
          muted:   'var(--accent-muted)',
          subtle:  'var(--accent-subtle)',
          glow:    'var(--accent-glow)',
          ring:    'var(--accent-ring)',
        },
        violet: {
          50:  'var(--violet-50)',
          200: 'var(--violet-200)',
          300: 'var(--violet-300)',
          400: 'var(--violet-400)',
          500: 'var(--violet-500)',
          600: 'var(--violet-600)',
          700: 'var(--violet-700)',
        },
        cyan: {
          DEFAULT: 'var(--cyan)',
          bg:      'var(--cyan-bg)',
          border:  'var(--cyan-border)',
        },
        txt: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted:     'var(--text-muted)',
          disabled:  'var(--text-disabled)',
          inverse:   'var(--text-inverse)',
        },
        border: {
          DEFAULT: 'var(--border-default)',
          subtle:  'var(--border-subtle)',
          strong:  'var(--border-strong)',
          accent:  'var(--border-accent)',
        },
        win:  { DEFAULT: 'var(--win)',  bg: 'var(--win-bg)',  border: 'var(--win-border)' },
        loss: { DEFAULT: 'var(--loss)', bg: 'var(--loss-bg)', border: 'var(--loss-border)' },
        warn: { DEFAULT: 'var(--warn)', bg: 'var(--warn-bg)', border: 'var(--warn-border)' },
        info: { DEFAULT: 'var(--info)', bg: 'var(--info-bg)', border: 'var(--info-border)' },
        team: {
          blue: 'var(--blue-team)',
          red:  'var(--red-team)',
        },
      },
      fontFamily: {
        sans:    ['"Geist"', '"Geist Sans"', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        display: ['"Fraunces"', '"Playfair Display"', 'Georgia', 'serif'],
        mono:    ['"Geist Mono"', '"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        '2xs':  ['10px', { lineHeight: '1.3' }],
        'xs':   ['11px', { lineHeight: '1.4' }],
        'sm':   ['12px', { lineHeight: '1.45' }],
        'base': ['13px', { lineHeight: '1.5' }],
        'md':   ['15px', { lineHeight: '1.5' }],
        'lg':   ['17px', { lineHeight: '1.4' }],
        'xl':   ['20px', { lineHeight: '1.35' }],
        '2xl':  ['24px', { lineHeight: '1.25' }],
        '3xl':  ['32px', { lineHeight: '1.18' }],
        '4xl':  ['42px', { lineHeight: '1.1' }],
      },
      borderRadius: {
        'xs': '2px',
        'sm': '4px',
        DEFAULT: '6px',
        'md': '6px',
        'lg': '10px',
        'xl': '14px',
        '2xl': '18px',
      },
      boxShadow: {
        'sm': '0 1px 2px rgba(0, 0, 0, 0.35)',
        DEFAULT: '0 2px 8px rgba(0, 0, 0, 0.4), 0 1px 2px rgba(0, 0, 0, 0.3)',
        'md': '0 4px 14px rgba(0, 0, 0, 0.4)',
        'lg': '0 10px 28px rgba(0, 0, 0, 0.45)',
        'xl': '0 20px 56px rgba(0, 0, 0, 0.55)',
        'glow':    '0 0 18px var(--accent-glow)',
        'glow-sm': '0 0 10px var(--accent-glow)',
        'glow-lg': '0 0 40px var(--accent-glow)',
        'inner-glow': 'inset 0 1px 0 rgba(255, 255, 255, 0.06)',
        'ring-accent': '0 0 0 1px var(--border-accent)',
      },
      backdropBlur: {
        xs: '4px',
      },
      spacing: {
        '18': '4.5rem',
      },
      letterSpacing: {
        'tighter': '-0.03em',
        'tight':   '-0.02em',
        'display': '-0.025em',
        'widest-2': '0.2em',
      },
    },
  },
  plugins: [],
};
